# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-19 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='taggeditem',
            index_together=set([('content_type', 'object_id')]),
        ),
    ]
