# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gemcore', '0001_squashed_0006_remove_entry_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='labels',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='entryhistory',
            old_name='tags_label',
            new_name='tags',
        ),
    ]
