# Generated by Django 3.1.2 on 2020-10-26 19:38

import django.contrib.postgres.fields
from django.db import migrations, models

from gemcore.constants import ChoicesMixin


class Migration(migrations.Migration):

    dependencies = [
        ('gemcore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='country',
            field=models.CharField(choices=ChoicesMixin.COUNTRY_CHOICES, max_length=2),
        ),
        migrations.AlterField(
            model_name='entryhistory',
            name='country_code',
            field=models.CharField(choices=ChoicesMixin.COUNTRY_CHOICES, max_length=2),
        ),
        migrations.AlterField(
            model_name='parserconfig',
            name='amount',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), help_text='Indexes start at 0, comma separated list of naturals.', size=2),
        ),
        migrations.AlterField(
            model_name='parserconfig',
            name='country',
            field=models.CharField(choices=ChoicesMixin.COUNTRY_CHOICES, max_length=2),
        ),
        migrations.AlterField(
            model_name='parserconfig',
            name='defer_processing',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, help_text='Indexes start at 0, comma separated list of strings.', size=None),
        ),
        migrations.AlterField(
            model_name='parserconfig',
            name='notes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, default=list, help_text='Indexes start at 0, comma separated list of naturals.', size=None),
        ),
        migrations.AlterField(
            model_name='parserconfig',
            name='what',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), help_text='Indexes start at 0, comma separated list of naturals.', size=None),
        ),
        migrations.AlterField(
            model_name='parserconfig',
            name='when',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), help_text='Indexes start at 0, comma separated list of naturals.', size=None),
        ),
    ]
