# Generated by Django 3.1.2 on 2021-02-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemcore', '0002_auto_20201026_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='parserconfig',
            name='ignore_rows_char',
            field=models.CharField(default='#', max_length=1),
        ),
        migrations.AddField(
            model_name='parserconfig',
            name='amount_extra',
            field=models.JSONField(help_text='Extra data to help parsing amounts: provide an extra column index, starting at 0, to be used for comparison against fixed values to indicate if the entry is an expense or an income. Must be a dict with keys: column_index (nat), expense_label (str), income_label (str).', null=True),
        ),
    ]
