# Generated by Django 3.2.7 on 2021-11-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemcore', '0002_auto_20201026_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parserconfig',
            name='ignore_rows',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
