# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gemcore', '0003_auto_20170622_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='parser',
        ),
        migrations.AlterField(
            model_name='account',
            name='parser_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gemcore.ParserConfig'),
        ),
    ]
