# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 23:27
from __future__ import unicode_literals

from django.db import migrations


def copy_tags(apps, schema_editor):
    Entry = apps.get_model('gemcore', 'Entry')
    for entry in Entry.objects.all():
        entry.labels = [k for k, v in entry.tags.items() if v]
        entry.save()


def clear_labels(apps, schema_editor):
    Entry = apps.get_model('gemcore', 'Entry')
    Entry.objects.all().update(labels=None)


class Migration(migrations.Migration):

    dependencies = [
        ('gemcore', '0003_auto_20170617_2026'),
    ]

    operations = [
        migrations.RunPython(copy_tags, reverse_code=clear_labels),
    ]
