# Generated by Django 3.1.2 on 2021-03-19 18:50

from django.db import migrations


TEST_SLUG = 'test'


def add_test_objects(apps, schema_editor):
    # We can't import the models directly as it may be a newer
    # version than this migration expects. We use the historical version.
    User = apps.get_model('auth', 'User')
    Book = apps.get_model('gemcore', 'Book')
    ParserConfig = apps.get_model('gemcore', 'ParserConfig')
    Account = apps.get_model('gemcore', 'Account')

    test_user = User.objects.create(username=TEST_SLUG)

    test_book = Book.objects.create(slug=TEST_SLUG, name=TEST_SLUG.capitalize())
    test_book.users.add(test_user)

    test_parser = ParserConfig.objects.create(
        name=TEST_SLUG, country='US', ignore_rows=0, ignore_rows_char='#',
        when=[0], what=[3], amount=[2], amount_extra={
            'column_index': 1,
            'income_label': 'Income',
            'expense_label': 'Expense'},
    )
    test_account = Account.objects.create(
        slug=TEST_SLUG, name=TEST_SLUG.capitalize(), currency='USD',
        parser_config=test_parser)
    test_account.users.add(test_user)
    test_account.tagregex_set.create(regex='.*', tag=TEST_SLUG)


def remove_test_objects(apps, schema_editor):
    # We can't import the models directly as it may be a newer
    # version than this migration expects. We use the historical version.
    User = apps.get_model('auth', 'User')
    Book = apps.get_model('gemcore', 'Book')
    ParserConfig = apps.get_model('gemcore', 'ParserConfig')
    Account = apps.get_model('gemcore', 'Account')

    User.objects.filter(username=TEST_SLUG).delete()
    Book.objects.filter(slug=TEST_SLUG).delete()
    ParserConfig.objects.filter(name=TEST_SLUG).delete()
    Account.objects.filter(slug=TEST_SLUG).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gemcore', '0003_parserconfig_extra_fields'),
    ]

    operations = [
        migrations.RunPython(add_test_objects, remove_test_objects),
    ]
