# Generated by Django 4.0.4 on 2022-05-02 01:15

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


OLD = 'maintainance'
NEW = 'maintenance'


def update_tag_name(apps, old, new):
    Entry = apps.get_model('gemcore', 'Entry')
    for entry in Entry.objects.filter(tags__contains=[old]):
        entry.tags = [t for t in entry.tags.copy() if t != old] + [new]
        entry.save()


def migrate_tags_foward(apps, schema_editor):
    update_tag_name(apps, OLD, NEW)


def migrate_tags_backward(apps, schema_editor):
    update_tag_name(apps, NEW, OLD)


class Migration(migrations.Migration):

    dependencies = [
        ('gemcore', '0003_alter_parserconfig_ignore_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('bureaucracy', 'bureaucracy'), ('car', 'car'), ('change', 'change'), ('children', 'children'), ('food', 'food'), ('fun', 'fun'), ('health', 'health'), ('house', 'house'), ('maintenance', 'maintenance'), ('other', 'other'), ('rent', 'rent'), ('taxes', 'taxes'), ('transportation', 'transportation'), ('utilities', 'utilities'), ('work-ish', 'work-ish'), ('imported', 'imported'), ('trips', 'trips')], max_length=256), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='entry',
            name='when',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='tagregex',
            name='tag',
            field=models.CharField(choices=[('bureaucracy', 'bureaucracy'), ('car', 'car'), ('change', 'change'), ('children', 'children'), ('food', 'food'), ('fun', 'fun'), ('health', 'health'), ('house', 'house'), ('maintenance', 'maintenance'), ('other', 'other'), ('rent', 'rent'), ('taxes', 'taxes'), ('transportation', 'transportation'), ('utilities', 'utilities'), ('work-ish', 'work-ish'), ('imported', 'imported'), ('trips', 'trips')], max_length=256),
        ),
        migrations.RunPython(migrate_tags_foward, migrate_tags_backward),
    ]
