# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 23:40
from __future__ import unicode_literals

import bitfield.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemcore', '0004_auto_copy_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('bureaucracy', 'bureaucracy'), ('car', 'car'), ('change', 'change'), ('food', 'food'), ('fun', 'fun'), ('health', 'health'), ('house', 'house'), ('maintainance', 'maintainance'), ('other', 'other'), ('rent', 'rent'), ('taxes', 'taxes'), ('transportation', 'transportation'), ('utilities', 'utilities'), ('work-ish', 'work-ish'), ('imported', 'imported'), ('trips', 'trips')], max_length=256), size=None),
        ),
        migrations.AlterField(
            model_name='entry',
            name='tags',
            field=bitfield.models.BitField([('bureaucracy', 'bureaucracy'), ('car', 'car'), ('change', 'change'), ('food', 'food'), ('fun', 'fun'), ('health', 'health'), ('house', 'house'), ('maintainance', 'maintainance'), ('other', 'other'), ('rent', 'rent'), ('taxes', 'taxes'), ('transportation', 'transportation'), ('utilities', 'utilities'), ('work-ish', 'work-ish'), ('imported', 'imported'), ('trips', 'trips')], default=None, null=True),
        ),
    ]
