# Generated by Django 4.1.5 on 2023-01-13 12:34

from django.db import migrations, models

from gemcore.constants import ChoicesMixin


class Migration(migrations.Migration):

    dependencies = [
        (
            'gemcore',
            '0004_alter_entry_tags_alter_entry_when_alter_tagregex_tag',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='parserconfig',
            name='delimiter',
            field=models.CharField(default=',', max_length=10),
        ),
        migrations.AlterField(
            model_name='entry',
            name='country',
            field=models.CharField(
                choices=ChoicesMixin.COUNTRY_CHOICES,
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name='entryhistory',
            name='country_code',
            field=models.CharField(
                choices=ChoicesMixin.COUNTRY_CHOICES,
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name='parserconfig',
            name='country',
            field=models.CharField(
                choices=ChoicesMixin.COUNTRY_CHOICES,
                max_length=2,
            ),
        ),
    ]
