# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gemcore', '0004_auto_20170622_2257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('currency', 'name')},
        ),
        migrations.RenameField(
            model_name='account',
            old_name='currency_code',
            new_name='currency',
        ),
    ]
