# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gemcore', '0005_auto_20170617_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='tags',
        ),
    ]
