# Generated by Django 5.0.3 on 2024-04-21 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gemcore", "0006_asset_entry_asset"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={"ordering": ("since", "name")},
        ),
        migrations.AddField(
            model_name="tagregex",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gemcore.asset",
            ),
        ),
    ]
