# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-21 21:34
from __future__ import unicode_literals

import bitfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemcore', '0014_auto_20160919_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='parser',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='entry',
            name='tags',
            field=bitfield.models.BitField([('bureaucracy', 'bureaucracy'), ('car', 'car'), ('change', 'change'), ('food', 'food'), ('fun', 'fun'), ('health', 'health'), ('house', 'house'), ('maintainance', 'maintainance'), ('other', 'other'), ('rent', 'rent'), ('taxes', 'taxes'), ('travel (transport)', 'travel (transport)'), ('utilities', 'utilities'), ('work(ish)', 'work(ish)'), ('imported', 'imported'), ('trips', 'trips'), ('investments', 'investments')], default=None),
        ),
    ]
