# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-08 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemcore', '0015_auto_20160921_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
