# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-10 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gemcore', '0016_account_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagRegex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regex', models.TextField()),
                ('tag', models.CharField(choices=[('bureaucracy', 'bureaucracy'), ('car', 'car'), ('change', 'change'), ('food', 'food'), ('fun', 'fun'), ('health', 'health'), ('house', 'house'), ('maintainance', 'maintainance'), ('other', 'other'), ('rent', 'rent'), ('taxes', 'taxes'), ('travel (transport)', 'travel (transport)'), ('utilities', 'utilities'), ('work(ish)', 'work(ish)'), ('imported', 'imported'), ('trips', 'trips'), ('investments', 'investments')], max_length=256)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gemcore.Account')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tagregex',
            unique_together=set([('account', 'regex', 'tag')]),
        ),
    ]
