# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gemcore', '0019_auto_20161230_1921'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set([('book', 'account', 'when', 'what', 'amount', 'is_income')]),
        ),
    ]
