name: 'Check reminders'

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

permissions:
  pull-requests: write
  issues: write

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Check reminders and notify
        uses: agrc/reminder-action@v1
