name: 'Create reminders'

on:
  workflow_dispatch:
  issue_comment:
    types: [created, edited]

permissions:
  pull-requests: write
  issues: write

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Check comments and create reminders
        uses: agrc/create-reminder-action@v1
