name: Django CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt -r requirements-devel.txt
        black --version
    - name: Check code style
      uses: psf/black@stable
    - name: Check linting
      run: |
        pip install flake8 isort
        flake8 --exclude=gemcore/migrations .
        isort --check .
    - name: Collect static files
      run: |
        python manage.py collectstatic
    - name: Run Tests
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432
        SECRET_KEY: testkey
      run: |
        python -Wall manage.py test -v 3
